"""
Underwater Acoustic Propagation Module
======================================

This module propagates clean audio source signals through simulated underwater acoustic 
environments generated by Bellhop. Each environment’s impulse response (IR) is convolved 
with the source signals to simulate underwater transmission effects.

Workflow:
---------
1. Load precomputed Bellhop impulse responses (.npy files).
2. Load clean source signals (.wav files).
3. Convolve each source with each impulse response (FFT convolution).
4. Normalize and save the resulting propagated signals as new .wav files.

Usage:
------
$ python propagate_sources.py

Author: Abdullah Abdelaziz
Created: 2025
"""

import os
import glob
import numpy as np
import pandas as pd
import soundfile as sf
from scipy.signal import fftconvolve
import arlpy.uwapm as pm
from environment_simulation import bellhop_envs


def main(
    bellhop_envs_path: str = None,
    source_dir: str = None,
    output_dir: str = None,
    fs: int = 16000
):
    """
    Propagate source signals through Bellhop-simulated underwater environments.

    This function loads impulse responses representing different underwater 
    acoustic conditions and convolves them with source signals to produce 
    propagated (underwater) audio outputs.

    Parameters
    ----------
    bellhop_envs_path : str, optional
        Path to the directory containing Bellhop impulse response files (.npy). 
        If not provided, the user will be prompted.
    source_dir : str, optional
        Directory containing clean source audio signals (.wav). 
        If not provided, the user will be prompted.
    output_dir : str, optional
        Directory to save the propagated outputs. 
        If not provided, the user will be prompted.
    fs : int, optional
        Target sampling frequency (Hz). Default is 16000.

    Returns
    -------
    None
        The propagated audio files are saved to the specified output directory.

    Notes
    -----
    - Impulse responses should be generated using `environment_simulation.py`.
    - Each propagated audio file is named:
      `{source_name}_propagated_{ir_filename}.wav`
    - The convolution is performed using FFT-based convolution for efficiency.
    """

    # === STEP 1: Bellhop environment path setup ==============================
    if bellhop_envs_path is None:
        ans = input("Do you have Bellhop environments? (Y/N): ").strip().lower()
        if ans in ['y', 'yes']:
            bellhop_envs_path = input("Please provide the path to Bellhop environments: ").strip()
        else:
            exit(
                "\nPlease generate Bellhop environments first.\n"
                "Use `environment_simulation.py` to create them."
            )

    if not os.path.exists(bellhop_envs_path):
        raise FileNotFoundError(f"Bellhop environment directory not found: {bellhop_envs_path}")

    print(f"Using Bellhop environments from: {bellhop_envs_path}")

    # === STEP 2: Source directory setup =====================================
    if source_dir is None:
        source_dir = input("Please provide the path to source signals: ").strip()
    if not os.path.exists(source_dir):
        raise FileNotFoundError(f"Source directory not found: {source_dir}")

    print(f"🎧 Using source signals from: {source_dir}")

    # === STEP 3: Output directory setup =====================================
    if output_dir is None:
        output_dir = input("Please provide the path to output directory: ").strip()
    os.makedirs(output_dir, exist_ok=True)
    print(f"output will be saved to: {output_dir}")

    # === STEP 4: Load source signals ========================================
    source_files = glob.glob(os.path.join(source_dir, "*.wav"))
    if not source_files:
        raise FileNotFoundError("No .wav source files found in the specified directory.")
    print(f"Found {len(source_files)} source signals.")

    # === STEP 5: Load Bellhop impulse responses =============================
    ir_files = glob.glob(os.path.join(bellhop_envs_path, "*.npy"))
    if not ir_files:
        raise FileNotFoundError("No impulse response (.npy) files found in the Bellhop environment directory.")
    print(f"Found {len(ir_files)} impulse response files.")

    # === STEP 6: Propagate each source through each environment =============
    for ir_file in ir_files:
        ir_name = os.path.splitext(os.path.basename(ir_file))[0]
        print(f"\nProcessing environment: {ir_name}")

        # Load impulse response
        ir = np.load(ir_file)

        for src_path in source_files:
            source_name = os.path.splitext(os.path.basename(src_path))[0]
            print(f"Propagating source: {source_name}")

            # Load audio file
            source, src_fs = sf.read(src_path)

            # Resample check
            if src_fs != fs:
                raise ValueError(
                    f"Source {source_name} sample rate {src_fs} != expected {fs}. "
                    "Please resample before processing."
                )

            # Convolution (FFT-based for performance)
            propagated = fftconvolve(source, ir, mode='full')

            # Convert to real-valued audio
            propagated_real = np.real(propagated)

            # Normalize audio to avoid clipping
            propagated_real /= np.max(np.abs(propagated_real) + 1e-12)

            # Construct output filename
            output_filename = f"{source_name}_propagated_{ir_name}.wav"
            output_path = os.path.join(output_dir, output_filename)

            # Save propagated signal
            sf.write(output_path, propagated_real.astype(np.float32), fs)

            print(f"Saved propagated audio: {output_path}")

    print("\All sources successfully propagated through all environments.")
    print("==============================================================")


if __name__ == "__main__":
    
    bellhop_envs_path= "../bellhop_envs"
    source_dir = "../sources/submarine/audio"
    output_dir = "../bellhop_out/submarine_propagated"
    
    main(
    bellhop_envs_path,
    source_dir,
    output_dir)